### PR TITLE
Adds DS_Store, VScode environments to gitignore

### PR DESCRIPTION
**Pull request by jlsnow301**
~~It also rhymes~~ Edit: after changing the title, it no longer rhymes. regressive update.

DS_Store is creating merge conflicts in #29 
It is a local file for apple users and needn't be in the repo

### CODE REVIEW

**Comment by jlsnow301** [comment]
Looks like some prior PRs have this already so I will be closing

**Comment by jlsnow301** [comment]
On further thought I think we should have it atomized into its own separate PR. This just has the gitignore additions, which should resolve some issues in other PRs

**Review by selinapn — APPROVED** [review]

**Review by VitaRox — APPROVED** [review]
This looks great!  Thanks for including the VsCode ones, too.  Approved!

**Comment by Raotrux** [comment]
Looks good. This is what I was doing for my gitignore as well.

**Review by Raotrux — APPROVED** [review]

**Pull request merged**
